import type { CadDocument } from './types';

export const sampleDocument: CadDocument = {
  id: 'sample-document',
  name: 'Sample 2D Drawing',
  units: 'mm',
  layers: [
    {
      id: 'layer-0',
      name: '기본',
      color: '#2563eb',
      visible: true,
      locked: false,
    },
    {
      id: 'layer-notes',
      name: '주석',
      color: '#16a34a',
      visible: true,
      locked: false,
    },
  ],
  entities: [
    {
      id: 'line-1',
      type: 'line',
      layerId: 'layer-0',
      rotation: 0,
      strokeColor: '#1f2937',
      fillColor: 'transparent',
      strokeWidth: 2,
      strokeStyle: 'solid',
      visible: true,
      locked: false,
      x1: -180,
      y1: -80,
      x2: 180,
      y2: -80,
    },
    {
      id: 'rect-1',
      type: 'rect',
      layerId: 'layer-0',
      rotation: 0,
      strokeColor: '#2563eb',
      fillColor: 'rgba(37, 99, 235, 0.08)',
      strokeWidth: 2,
      strokeStyle: 'solid',
      visible: true,
      locked: false,
      x: -160,
      y: -40,
      width: 220,
      height: 120,
    },
    {
      id: 'circle-1',
      type: 'circle',
      layerId: 'layer-0',
      rotation: 0,
      strokeColor: '#dc2626',
      fillColor: 'rgba(220, 38, 38, 0.08)',
      strokeWidth: 2,
      strokeStyle: 'solid',
      visible: true,
      locked: false,
      cx: 150,
      cy: 35,
      radius: 48,
    },
    {
      id: 'text-1',
      type: 'text',
      layerId: 'layer-notes',
      rotation: 0,
      strokeColor: '#166534',
      fillColor: '#166534',
      strokeWidth: 1,
      strokeStyle: 'solid',
      visible: true,
      locked: false,
      x: -155,
      y: 110,
      content: 'SimpleCAD 샘플 도면',
      fontSize: 18,
    },
  ],
};
